### ISSUE TITLE
Unable to find item without range key

### ISSUE THREAD

**Issue by ruandre** [victorquinn/dynasty#83]
When trying to find an item without a range key ...
```js
var promise = table.find({ hash: 'some-user-id', range: 'some-date' }) // works
var promise = table.find('some-user-id') // fails, see error below:
```
... I get this:
```
Unhandled rejection ValidationException: The provided key element does not match the schema
    at Request.extractError (/app/node_modules/aws-sdk/lib/protocol/json.js:43:27)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:598:12)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:37:9)
```

Any ideas as to why this happens? Is it mandatory to supply the range key?

**Comment by ruandre** [comment]
Ah, turns out you have to specify both the hash and range keys :crying_cat_face:
